### ISSUE TITLE
Align Open Competencies to the Great Schools Partnership model

### ISSUE THREAD

**Issue by ehmatthes** [openlearningtools/opencompetencies#41]
This is a major reboot of the Open Competencies project. The current model is one we developed in-house at my school; we've decided to work from an existing model, rather than developing our own. There is no change in philosophy, just a moderate structural change. This alignment will also simplify the existing project, and focus on use of the simplest aspect of Open Competencies before building out more features.

Alignment Checklist
---
- [x] Get Open Competencies up and running locally again. #42
- [x] Update project to Django 1.8. #43 #44
- [x] Simplify homepage. #45
- [x] Outline user interface. #47
- [x] Update model. #49
- [x] Update views. (done in #49)
- [x] Update entry process. (done in #49)
- [x] Update user registration system. #57
- [x] Update licensing issues. #58
    - [x] Modify code license to MIT.
    - [x] Does it also need a CC license for content? #46
- ~~[ ] Update tests. (This means removing irrelevant tests, not writing new tests at this point.)~~
    - ~~[ ] Start a list of highest priority tests to write.~~
    - Moved to #48.
- [x] Push changes to live site. #59.
